### PR TITLE
test(scripts): load update_versions by path to avoid scripts-package shadow (#1311)

### LINKED ISSUE #1311: [Bug] tests/scripts/test_update_versions.py fails during collection without PYTHONPATH
### Description

When running the test suite from a fresh checkout:

    uv run pytest

pytest fails during collection with:

```bash
ImportError: cannot import name 'update_versions' from 'scripts'
(.../tests/scripts/__init__.py)
```

However, the test passes when the repository root is explicitly added to PYTHONPATH:

    PYTHONPATH=$PWD uv run pytest tests/scripts/test_update_versions.py

This appears to be caused by `tests/scripts` shadowing the top-level `scripts` module during import resolution.

Environment:
- Fedora 43 - WSL
- Python 3.12.13
- uv
- pytest 9.0.3

I'd be happy to submit a PR if this is the intended direction for fixing it.

### Steps to reproduce

_No response_

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by abhay-codes07**
## Related issue

Closes #1311

## Summary

- `tests/scripts/test_update_versions.py` imported the script under test with `from scripts import update_versions`. The repo-root `scripts/` is a **namespace** package (no `__init__.py`), while `tests/scripts/` is a **regular** package — so during a full-suite `uv run pytest`, the regular `tests/scripts` package resolves as the top-level `scripts` (pytest's default "prepend" import mode) and shadows the namespace package. Collection then fails with `ImportError: cannot import name 'update_versions' from 'scripts' (.../tests/scripts/__init__.py)`. The test passes in isolation / with `PYTHONPATH=$PWD`, which is why it only surfaces in a full run.
- Load `scripts/update_versions.py` by its repo-root **file path** via `importlib.util` instead, which is immune to the package-name collision and no longer depends on `scripts` being importable. The module is registered in `sys.modules` before `exec_module` so its `@dataclass` definitions resolve their defining module during class creation.

Why this approach over the alternatives I tried:
- **Removing `tests/scripts/__init__.py`** does fix the shadow, but it makes running `pytest tests/scripts` directly fail (the dir's other tests error without the package), so it trades one breakage for another.
- **Switching the suite to `importmode=importlib`** is far broader than this one test and risks the whole suite.

The file-path load is localized to the one affected test and changes no production code or suite-wide behavior.

## Test Plan

On Windows (this checkout) the full collection has pre-existing POSIX-only collection errors; the relevant before/after for this issue:

- **Before:** `uv run pytest --co tests/` → `ERROR collecting tests/scripts/test_update_versions.py` (`ImportError: cannot import name 'update_versions' from 'scripts'`). Total: 23 collection errors.
- **After:** that module collects cleanly (`<Module test_update_versions.py>`); total drops to **22** (the remaining 22 are unrelated POSIX-only errors on Windows). I fixed exactly one and introduced none.
- `uv run pytest tests/scripts/test_update_versions.py` → **10 passed**, including with `-o pythonpath=` (confirms the load no longer depends on `scripts` being on the path).
- `uv run pytest --co tests/scripts` → still 59 collected, clean.
- `ruff check` / `ruff format --check` on the file: clean.

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Refactor / chore
- [ ] Docs
- [x] Test / CI
- [ ] Breaking change

## Test coverage

- [ ] Unit tests added / updated
- [ ] Integration tests added / updated
- [ ] E2E tests added / updated
- [x] Manual verification completed
- [x] Existing tests cover this change
- [ ] Not applicable

## Coverage notes

This change only fixes how an existing test module imports the code under test; there is no production code change, so no new test is warranted. Verified manually by reproducing the exact collection `ImportError` from #1311 in a full-suite `pytest --co` run, applying the fix, and confirming the module then collects and its 10 tests pass (and that the total collection-error count drops by exactly one, with no new failures). No secrets involved.

### CODE REVIEW

**Comment by abhay-codes07** [comment]
hi @PattaraS kindly check and review it

**Review by PattaraS — APPROVED** [review]
Thanks for the contribution! This LGTM.
